// Generated by CoffeeScript 1.3.3
(function() {
  var _this = this;

  $('.main-nav').scrollspy({
    offset: 200
  });

  $('.main-nav').find('a').on('click', function(e) {
    var id;
    e.preventDefault();
    id = $(e.target).attr('href');
    return _this.scrollTo(id, 150);
  });

  $('.main-nav li').on('activate', function(e) {
    var id;
    id = $(e.target).find('a').attr('href');
    return _this.scrollTo(id, 150);
  });

  this.scrollTo = function(id, offset) {
    var yPos;
    yPos = $(id).position().top - offset;
    return $(document.body).scrollTo(yPos, 500);
  };

}).call(this);
